### ISSUE TITLE
Warning: Calling bottle :unneeded is deprecated! There is no replacement

### ISSUE THREAD

**Issue by dineshbhagat** [tednaleid/ganda#2]
I have installed `ganda` from homebrew.
```
brew tap tednaleid/homebrew-ganda
brew install ganda
```
Once installation is complete, following warning from homebrew.
This warning occurs during every `brew update` or `brew upgrade` command.
```
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the tednaleid/ganda tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/tednaleid/homebrew-ganda/Formula/ganda.rb:6
```

Possible solutions:
- https://stackoverflow.com/a/45163490/2987755
- Might need to update [goreleaser](https://github.com/goreleaser/goreleaser/releases/tag/v1.1.0) Ref:https://github.com/FairwindsOps/homebrew-tap/issues/6

**Comment by tednaleid** [comment]
Thanks for the report!  I'll look at getting this cleaned up so it no longer throws this error on install

**Comment by tednaleid** [comment]
Ok, the latest version should fix this issue, I'm no longer seeing `Calling bottle :unneeded` after installing the latest:

```
ganda --version
ganda version 0.1.10
```

There will be one last warning that pops out when it is upgrading and removing `0.1.8`, but after that it should be gone.

If anyone is still seeing this error, I'd follow these steps to uninstall/untap, and then reinstall:

```
brew uninstall ganda
brew untap tednaleid/homebrew-ganda
brew cleanup
brew tap tednaleid/homebrew-ganda
brew install ganda
```

```
brew list ganda
/usr/local/Cellar/ganda/0.1.10/bin/ganda
ganda --version
ganda version 0.1.10
```

I'll close this issue out, but let me know if you're still seeing issues.

**Comment by dineshbhagat** [comment]
Thank you @tednaleid !!!
