### ISSUE TITLE
How do I specify a new output file to be created for each post request

### ISSUE THREAD

**Issue by TechieGenie** [tednaleid/ganda#5]
Hi, I'm using `ganda` to make 100s of post requests where the URL is the same but the body changes and I want to capture the output of all the requests. Currently I'm specifying the output directory using the `-o datadir` flag. But the directory ends up with the output of the last invoked request.

How do I specify a new file to be created for each request ~~or append the API response to the existing file~~?

Sorry, if this is not the right forum to ask this question. I didn't find any alternate way, so creating the issue.

**Comment by TechieGenie** [comment]
I can simply append by redirecting the output. 

```shell
cat urls | ganda  >> append.txt
```

**Comment by tednaleid** [comment]
ah! that's a use case I hadn't considered before.  With the url staying the same, it'll write the file to the same directory

This is a bit of a hack, but one idea would be to append a unique bookmark to the end of the url with the identifier that is being changed in the body.  

`ganda` should make the request to the same url, but the local url would have the bookmark.  bookmarks aren't transmitted as part of the http url.  Here's an example:

```
seq 5 | awk '{printf "http://httpbin.org/uuid#%s\n", $1}' |\
ganda -o output
Response: 200 http://httpbin.org/uuid#1 -> output/http-httpbin-org-uuid-1
Response: 200 http://httpbin.org/uuid#2 -> output/http-httpbin-org-uuid-2
Response: 200 http://httpbin.org/uuid#3 -> output/http-httpbin-org-uuid-3
Response: 200 http://httpbin.org/uuid#4 -> output/http-httpbin-org-uuid-4
Response: 200 http://httpbin.org/uuid#5 -> output/http-httpbin-org-uuid-5

cat output/http-httpbin-org-uuid-1
{
  "uuid": "27796526-d4be-4710-b3d9-4d2e13b990fd"
}
```

**Comment by TechieGenie** [comment]
Woah!! Didn't know that. Nice hack BTW.. Serves the purpose. 👍

**Comment by tednaleid** [comment]
Cool.  One thing I like about this solution is that it lets the file names have some meaning as it can include whatever ID is changing inside the body that's being posted.  Without that, we'd have to use some sort of random identifier that would make it hard to correlate specific requests with their contents.

I'll close this issue as it sounds like this approach will work for you.
